name: Build & Tag Wordpress Plugins.
description: "Build and tag Wordpress plugins with the version number."

on:
  workflow_dispatch:
    inputs:
      bump_level:
        type: choice
        description: Bump Level
        options:
          - prepatch
          - patch
          - minor
          - major
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun install

      - name: Ouput Debug Information
        run: |
          echo "Bump Level: {{ inputs.bump_level }}"
          echo "Release Version: $(bun run release-it {{ inputs.bump_level }} --release-version )"
          ls -la

      - name: debug git
        run: |
          git status

      - name: bump version
        run: |
          bun run release-it {{ inputs.bump_level }} --ci

      - name: Capture release version
        id: capture_version
        run: echo "RELEASE_VERSION=$(bun run release-it {{ inputs.bump_level }} --release-version )"" >> $GITHUB_ENV

      - name: Zip directory leaving out node_modules and .git
        run: |
          dir_name=$(basename "$PWD")
          zip -r "${dir_name}.zip" . -x "node_modules/*" -x ".git/*" -x ".release-it.json" -x ".github/*"

      # - name: Create a Release
      #   uses: elgohr/Github-Release-Action@v5
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     title: Release ${{ steps.capture_version.outputs.RELEASE_VERSION }}
      #     prerelease: ${{ inputs.bump_level == 'prepatch' }}
      #     tag: ${{ steps.capture_version.outputs.RELEASE_VERSION }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ steps.capture_version.outputs.RELEASE_VERSION }}
          tag_name: ${{ steps.capture_version.outputs.RELEASE_VERSION }}
          prerelease: ${{ inputs.bump_level == 'prepatch' }}
          files: |
            *.zip
