name: Build & Tag Wordpress Plugins.
description: "Build and tag Wordpress plugins with the version number."

on:
  workflow_dispatch:
    inputs:
      bump_level:
        type: choice
        description: Bump Level
        options:
          - prepatch
          - patch
          - minor
          - major
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: release

      - uses: php-actions/composer@v6
        with:
          working_dir: "release"

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          cd release
          bun install
          git checkout bun.lockb

      - name: Ouput Debug Information
        run: |
          cd release
          echo "Bump Level: {{ inputs.bump_level }}"
          echo "Release Version: $(bun run release-it {{ inputs.bump_level }} --release-version )"
          ls -la

      - name: debug git
        run: |
          cd release
          git status

      - name: bump version
        run: |
          cd release
          bun run release-it {{ inputs.bump_level }} --ci

      - name: Capture release version
        id: capture_version
        run: |
          cd release
          echo "RELEASE_VERSION=$(bun run release-it {{ inputs.bump_level }} --release-version )"" >> $GITHUB_ENV

      # - name: Zip directory leaving out node_modules and .git
      #   run: |

      #     zip -r "${dir_name}.zip" ./release -x "node_modules/*" -x ".git/*" -x ".release-it.json" -x ".github/*"

      - name: Debug folder status
        run: |
          ls -la

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     name: Release ${{ steps.capture_version.outputs.RELEASE_VERSION }}
      #     tag_name: ${{ steps.capture_version.outputs.RELEASE_VERSION }}
      #     prerelease: ${{ inputs.bump_level == 'prepatch' }}
      #     files: |
      #       *.zip
