name: Build & Tag Wordpress Plugins.
description: "Build and tag Wordpress plugins with the version number."

on:
  workflow_dispatch:
    inputs:
      bump_level:
        type: choice
        description: Bump Level
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
      prerelease-id:
        type: choice
        description: Prerelease ID
        options:
          - alpha
          - beta
          - rc
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: release

      - uses: php-actions/composer@v6
        with:
          working_dir: "release"

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          cd release
          bun install
          git checkout bun.lockb

      ## Current Version
      - name: Capture Current Version
        id: capture_current_version
        run: |
          cd release
          echo "CURRENT_VERSION=$(bun release-it --release-version --no-increment)" >> $GITHUB_ENV
          echo ${{ env.CURRENT_VERSION }}

      ## End Current Version

      ## GET the command to check the version we will be updating to.
      - name: Get Update Version
        run: |
          if [[ "${{ env.CURRENT_VERSION }}" == *-* ]]; then
            echo "PRE_RELEASE=--preRelease" >> $GITHUB_ENV
            echo "RELEASE_VERSION=--release-version" >> $GITHUB_ENV
            echo "BUMP_LEVEL=" >> $GITHUB_ENV
            echo "PRE_RELEASE_ID=" >> $GITHUB_ENV
          else
            if [[ "${{ inputs.bump_level }}" == pre* ]]; then
              echo "PRE_RELEASE=" >> $GITHUB_ENV
              echo "RELEASE_VERSION=--release-version" >> $GITHUB_ENV
              echo "BUMP_LEVEL=${{ inputs.bump_level }}" >> $GITHUB_ENV
              echo "PRE_RELEASE_ID=--preReleaseId=${{ inputs.prerelease-id }}" >> $GITHUB_ENV
            else
              echo "PRE_RELEASE=" >> $GITHUB_ENV
              echo "RELEASE_VERSION=--release-version" >> $GITHUB_ENV
              echo "BUMP_LEVEL=${{ inputs.bump_level }}" >> $GITHUB_ENV
              echo "PRE_RELEASE_ID=" >> $GITHUB_ENV
            fi
          fi
          echo "RELEASE_VERSION=$(bun release-it ${{ env.BUMP_LEVEL }} ${{ env.RELEASE_VERSION }} ${{ env.PRE_RELEASE }} ${{ env.PRE_RELEASE_ID }})" >> $GITHUB_ENV
          echo ${{ env.RELEASE_VERSION }}

      # - name: Debug Update Version Command string
      #   run: |
      #     echo ${{ env.RELEASE_VERSION_COMMAND }}
      # ## End Update Version
      # ## Release Version
      # - name: Capture Release Version
      #   run: |
      #     cd release
      #     $RELEASE_VERSION_COMMAND

      # - name: Debug Release Version
      #   run: |
      #     echo "${{ env.RELEASE_VERSION }}"

      ## End Release Version

      # ## Get Release Command
      # - name: Determine Release Command
      #   id: determine_release_command
      #   run: |
      #     if [[ "${{ env.CURRENT_VERSION }}" == *-* ]]; then
      #       echo "RELEASE_COMMAND='bun release-it --preRelease'" >> $GITHUB_ENV
      #     else
      #       if [[ "${{ inputs.bump_level }}" == pre* ]]; then
      #         echo "RELEASE_COMMAND='bun release-it ${{ inputs.bump_level }} --preReleaseId=${{ inputs.prerelease-id }}'" >> $GITHUB_ENV
      #       else
      #         echo "RELEASE_COMMAND='bun release-it ${{ inputs.bump_level }}'" >> $GITHUB_ENV
      #       fi
      #     fi

      # - name: Debug Determine Release Command
      #   run: |
      #     echo ${{ env.RELEASE_COMMAND }}

      # ## End Get Release Command

      # - name: bump version
      #   run: |
      #     cd release
      #     eval $RELEASE_COMMAND

# - name: Zip directory leaving out node_modules and .git
#   run: |

#     zip -r "${dir_name}.zip" ./release -x "node_modules/*" -x ".git/*" -x ".release-it.json" -x ".github/*"

# - name: Debug folder status
#   run: |
#     ls -la

# - name: Release
#   uses: softprops/action-gh-release@v2
#   if: startsWith(github.ref, 'refs/tags/')
#   with:
#     name: Release ${{ steps.capture_version.outputs.RELEASE_VERSION }}
#     tag_name: ${{ steps.capture_version.outputs.RELEASE_VERSION }}
#     prerelease: ${{ inputs.bump_level == 'prepatch' }}
#     files: |
#       *.zip
