name: Build & Tag Wordpress Plugins.
description: "Build and tag Wordpress plugins with the version number."

on:
  workflow_dispatch:
    inputs:
      bump_level:
        type: choice
        description: Bump Level
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
      prerelease-id:
        type: choice
        description: Prerelease ID
        options:
          - alpha
          - beta
          - rc
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: release

      - uses: php-actions/composer@v6
        with:
          working_dir: "release"

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          cd release
          bun install
          git checkout bun.lockb

      - name: Capture Current Version
        id: capture_current_version
        run: |
          cd release
          echo "CURRENT_VERSION=$(bun release-it --release-version --no-increment)" >> $GITHUB_ENV

      - name: Set Update Version Flags
        run: |
          if [[ "${{ inputs.bump_level }}" == pre* ]]; then
            if [[ "${{ env.CURRENT_VERSION }}" == *-* ]]; then
              echo "PRE_RELEASE=--preRelease" >> $GITHUB_ENV
              echo "BUMP_LEVEL=" >> $GITHUB_ENV
              echo "PRE_RELEASE_ID=" >> $GITHUB_ENV
            else
              echo "PRE_RELEASE=" >> $GITHUB_ENV
              echo "BUMP_LEVEL=${{ inputs.bump_level }}" >> $GITHUB_ENV
              echo "PRE_RELEASE_ID=--preReleaseId=${{ inputs.prerelease-id }}" >> $GITHUB_ENV
            fi
          else
            echo "PRE_RELEASE=" >> $GITHUB_ENV
            echo "BUMP_LEVEL=${{ inputs.bump_level }}" >> $GITHUB_ENV
            echo "PRE_RELEASE_ID=" >> $GITHUB_ENV
          fi

      - name: Capture Update Version
        id: capture_release_version
        run: |
          cd release
          echo "RELEASE_VERSION=$(bun release-it ${{env.BUMP_LEVEL}} ${{env.PRE_RELEASE}} ${{env.PRE_RELEASE_ID}} --release-version)" >> $GITHUB_ENV

      - name: Bump The Version
        id: bump_version
        run: |
          cd release
          "$(bun release-it ${{env.BUMP_LEVEL}} ${{env.PRE_RELEASE}} ${{env.PRE_RELEASE_ID}})"

# - name: Zip directory leaving out node_modules and .git
#   run: |

#     zip -r "${dir_name}.zip" ./release -x "node_modules/*" -x ".git/*" -x ".release-it.json" -x ".github/*"

# - name: Debug folder status
#   run: |
#     ls -la

# - name: Release
#   uses: softprops/action-gh-release@v2
#   if: startsWith(github.ref, 'refs/tags/')
#   with:
#     name: Release ${{ steps.capture_version.outputs.RELEASE_VERSION }}
#     tag_name: ${{ steps.capture_version.outputs.RELEASE_VERSION }}
#     prerelease: ${{ inputs.bump_level == 'prepatch' }}
#     files: |
#       *.zip
